<?php $emptyKey = match($type){'product'=>'marketplace.empty','restaurant'=>'food.empty','provider'=>'healthcare.empty','course'=>'education.empty','job'=>'jobs.empty',default=>'news.empty'}; $typeKey = match($type){'product'=>'marketplace.product','restaurant'=>'food.title','provider'=>'healthcare.title','course'=>'education.title','job'=>'jobs.title',default=>'news.title'}; ?>
<section class="page-head"><div><span class="eyebrow"><?=e(__('ui.service'))?></span><h1><?=e($heading)?></h1><p><?=e($subtitle)?></p></div><form class="search-form" method="get"><input type="search" name="q" value="<?=e($search)?>" placeholder="<?=e(__('common.search'))?>"><button class="btn primary" type="submit"><?=e(__('common.search'))?></button></form></section>
<?php if(!$items): ?><div class="empty-state"><div class="empty-mark">—</div><h2><?=e(__('common.no_results'))?></h2><p><?=e(__($emptyKey))?></p></div><?php else: ?><div class="card-grid"><?php foreach($items as $item): ?><article class="content-card"><div class="card-top"><span class="tag"><?=e(__($typeKey))?></span><?php if(isset($item['base_price'])):?><strong><?=e(money($item['base_price']))?></strong><?php elseif(isset($item['price'])):?><strong><?=e(money($item['price']))?></strong><?php endif;?></div>
<?php if($type==='product'): ?><h3><?=e($item['name'])?></h3><p><?=e($item['description'] ?: '')?></p><small><?=e($item['business_name'])?></small><a class="text-link" href="<?=e(url('/marketplace/'.$item['id']))?>"><?=e(__('common.view'))?> →</a>
<?php elseif($type==='restaurant'): ?><h3><?=e($item['name'])?></h3><p><?=e($item['description'] ?: '')?></p><small><?=e($item['city'] ?: $item['business_name'])?></small><a class="text-link" href="<?=e(url('/food/'.$item['id']))?>"><?=e(__('common.view'))?> →</a>
<?php elseif($type==='provider'): ?><h3><?=e($item['business_name'])?></h3><p><?=e($item['professional_title'] ?: '')?></p><a class="text-link" href="<?=e(url('/healthcare/'.$item['id']))?>"><?=e(__('common.view'))?> →</a>
<?php elseif($type==='course'): ?><h3><?=e($item['title'])?></h3><p><?=e($item['description'] ?: '')?></p><small><?=e($item['institution_name'])?></small><form method="post" action="<?=e(url('/education/enroll/'.$item['id']))?>" class="inline-form"><?=csrf_field()?><button class="btn primary" type="submit"><?=e(__('education.enroll'))?></button></form>
<?php elseif($type==='job'): ?><h3><?=e($item['title'])?></h3><p><?=e(mb_strimwidth(strip_tags($item['description']),0,180,'…'))?></p><small><?=e($item['business_name'])?> · <?=e($item['employment_type'])?> · <?=e($item['workplace_type'])?></small><form method="post" action="<?=e(url('/jobs/apply/'.$item['id']))?>" class="apply-form"><?=csrf_field()?><textarea name="cover_letter" rows="3" placeholder="<?=e(__('jobs.cover_letter'))?>"></textarea><button class="btn primary" type="submit"><?=e(__('jobs.apply'))?></button></form>
<?php else: ?><h3><?=e($item['title'])?></h3><p><?=e($item['excerpt'] ?: mb_strimwidth(strip_tags($item['content']??''),0,180,'…'))?></p><a class="text-link" href="<?=e(url('/news/'.$item['id']))?>"><?=e(__('news.read'))?> →</a><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?>
