<?php

declare(strict_types=1);
namespace App\Controllers;
use App\Core\{Auth,Csrf,Request,Response,Validator,View,Logger}; use App\Repositories\UserRepository;
final class AuthController {
 private UserRepository $users; public function __construct(){ $this->users=new UserRepository(); }
 public function loginForm(Request $r,array $p=[]):void{ if(Auth::check())Response::redirect('/dashboard'); View::render('auth/login',['title'=>__('auth.login'),'errors'=>[]]); }
 public function login(Request $r,array $p=[]):void{ if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));Response::redirect('/login');} $email=trim((string)$r->post('email'));$password=(string)$r->post('password');$remember=(bool)$r->post('remember');$u=$this->users->findByEmail($email);$locked=$u && $u['locked_until'] && strtotime($u['locked_until'])>time(); if(!$u||$locked||!password_verify($password,$u['password_hash'])){if($u){$count=(int)$u['failed_login_count']+1;$until=$count>=5?gmdate('Y-m-d H:i:s',time()+900):null;$this->users->updateLoginFailure((int)$u['id'],$count,$until);}flash('error',__('auth.login_failed'));Response::redirect('/login');} $this->users->updateLoginSuccess((int)$u['id']);Auth::login($u);if($remember){$raw=bin2hex(random_bytes(32));$this->users->addRememberToken((int)$u['id'],$raw,gmdate('Y-m-d H:i:s',time()+((int)config('app.remember_days')*86400)));setcookie('tuniverse_remember',$raw,['expires'=>time()+((int)config('app.remember_days')*86400),'path'=>'/','secure'=>(bool)config('security.cookie_secure'),'httponly'=>true,'samesite'=>'Lax']);}Logger::write('security','login_success',['user_id'=>$u['id']]);flash('success',__('auth.login'));Response::redirect('/dashboard'); }
 public function registerForm(Request $r,array $p=[]):void{ if(Auth::check())Response::redirect('/dashboard'); View::render('auth/register',['title'=>__('auth.register'),'errors'=>[]]); }
 public function register(Request $r,array $p=[]):void{ if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));Response::redirect('/register');} $email=mb_strtolower(trim((string)$r->post('email')));$phone=trim((string)$r->post('phone'));$password=(string)$r->post('password');$confirm=(string)$r->post('confirm_password');$first=trim((string)$r->post('first_name'));$last=trim((string)$r->post('last_name'));$v=(new Validator())->required('first_name',$first,__('validation.required'))->required('last_name',$last,__('validation.required'))->required('email',$email,__('validation.required'));if(!filter_var($email,FILTER_VALIDATE_EMAIL))$v->email('email',$email,__('validation.email'));if($this->users->findByEmail($email)){$v->required('email','','');$errors=['email'=>__('auth.email_exists')];}else{$errors=[];}if(strlen($password)<(int)config('security.password_min_length'))$errors['password']=__('auth.password_short');if($password!==$confirm)$errors['confirm_password']=__('auth.password_mismatch');if($v->fails())$errors=array_merge($errors,$v->errors());if($errors){remember_old($_POST);View::render('auth/register',['title'=>__('auth.register'),'errors'=>$errors]);return;} $id=$this->users->create(['email'=>$email,'phone'=>$phone,'password_hash'=>password_hash($password,PASSWORD_DEFAULT),'first_name'=>$first,'last_name'=>$last,'display_name'=>trim($first.' '.$last),'locale'=>in_array($_POST['locale']??'',config('app.supported_locales'),true)?$_POST['locale']:'fr']);clear_old();Logger::write('security','registration',['user_id'=>$id]);flash('success',__('auth.registered'));Response::redirect('/login'); }
 public function logout(Request $r,array $p=[]):never{Auth::logout();}
 public function forgotForm(Request $r,array $p=[]):void{View::render('auth/forgot',['title'=>__('auth.reset')]);}
 public function forgot(Request $r,array $p=[]):void{if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));Response::redirect('/forgot-password');}$email=mb_strtolower(trim((string)$r->post('email')));$u=$this->users->findByEmail($email);if($u){$raw=bin2hex(random_bytes(32));$this->users->createResetToken((int)$u['id'],$raw,gmdate('Y-m-d H:i:s',time()+3600));$link=url('/reset-password/'.$raw);Logger::write('mail','password_reset_created',['email'=>$email,'link'=>$link]);}flash('success',__('auth.reset_sent'));Response::redirect('/login');}
 public function resetForm(Request $r,array $p=[]):void{View::render('auth/reset',['title'=>__('auth.reset'),'token'=>$p['token']??'']);}
 public function reset(Request $r,array $p=[]):void{if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));Response::redirect('/reset-password/'.rawurlencode((string)$p['token']));}$token=(string)($p['token']??'');$row=$this->users->findResetToken($token);$password=(string)$r->post('password');$confirm=(string)$r->post('confirm_password');if(!$row||strlen($password)<(int)config('security.password_min_length')||$password!==$confirm){flash('error',!$row?__('auth.invalid_token'):($password!==$confirm?__('auth.password_mismatch'):__('auth.password_short')));Response::redirect('/reset-password/'.rawurlencode($token));}$this->users->resetPassword((int)$row['user_id'],(int)$row['id'],password_hash($password,PASSWORD_DEFAULT));Logger::write('security','password_reset',['user_id'=>$row['user_id']]);flash('success',__('auth.reset_done'));Response::redirect('/login');}
}
