<?php
declare(strict_types=1); namespace App\Controllers;
use App\Core\{Authorization,Auth,Csrf,Request,Response,Validator,View}; use App\Repositories\BusinessRepository;
final class BusinessController {
 private BusinessRepository $repo; public function __construct(){ $this->repo=new BusinessRepository(); }
 public function index(Request $r,array $p=[]):void{Authorization::requireLogin();$owner=(new \App\Repositories\UserRepository())->hasPermission((int)Auth::id(),'business.view'); if(!$owner && !(new \App\Repositories\UserRepository())->hasPermission((int)Auth::id(),'business.create')){http_response_code(403);View::render('errors/403');return;}View::render('modules/business',['title'=>__('business.title'),'businesses'=>$this->repo->mine((int)Auth::id()),'products'=>$this->repo->byOwnerProducts((int)Auth::id())]);}
 public function createForm(Request $r,array $p=[]):void{Authorization::requirePermission('business.create');View::render('modules/business-create',['title'=>__('business.create'),'categories'=>$this->repo->categories(),'errors'=>[]]);}
 public function create(Request $r,array $p=[]):void{Authorization::requirePermission('business.create');if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));Response::redirect('/business/create');}$name=trim((string)$r->post('name'));$description=trim((string)$r->post('description'));$cat=(int)$r->post('category_id');$v=(new Validator())->required('name',$name,__('validation.required'));if($v->fails()){View::render('modules/business-create',['title'=>__('business.create'),'categories'=>$this->repo->categories(),'errors'=>$v->errors()]);return;}$this->repo->create((int)Auth::id(),$name,slugify($name),$description,$cat?:null);flash('success',__('business.created'));Response::redirect('/business');}
 public function productForm(Request $r,array $p=[]):void{Authorization::requirePermission('product.create');$mine=$this->repo->mine((int)Auth::id());View::render('modules/product-create',['title'=>__('marketplace.add'),'businesses'=>$mine,'errors'=>[]]);}
 public function productCreate(Request $r,array $p=[]):void{Authorization::requirePermission('product.create');if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));Response::redirect('/business/product/create');}$name=trim((string)$r->post('name'));$price=(float)$r->post('price');$business=(int)$r->post('business_id');$v=(new Validator())->required('name',$name,__('validation.required'))->numericPositive('price',$price,__('validation.invalid'));if($v->fails()){View::render('modules/product-create',['title'=>__('marketplace.add'),'businesses'=>$this->repo->mine((int)Auth::id()),'errors'=>$v->errors()]);return;}$this->repo->createProduct((int)Auth::id(),$business,$name,slugify($name),trim((string)$r->post('description')),$price);flash('success',__('common.created'));Response::redirect('/business');}
}
