<?php
declare(strict_types=1); namespace App\Controllers;
use App\Core\{Authorization,Auth,Csrf,Request,Response,Translation,Validator,View}; use App\Repositories\{ContentRepository,ModuleRepository}; use App\Repositories\BusinessRepository;
final class ModuleController {
 private ContentRepository $content; private ModuleRepository $module; private BusinessRepository $business;
 public function __construct(){ $this->content=new ContentRepository();$this->module=new ModuleRepository();$this->business=new BusinessRepository(); }
 public function marketplace(Request $r,array $p=[]):void{ $search=trim((string)$r->query('q',''));View::render('modules/list',['title'=>__('marketplace.title'),'heading'=>__('marketplace.title'),'subtitle'=>__('marketplace.subtitle'),'items'=>$this->content->products($search),'type'=>'product','search'=>$search]); }
 public function food(Request $r,array $p=[]):void{$search=trim((string)$r->query('q',''));View::render('modules/list',['title'=>__('food.title'),'heading'=>__('food.title'),'subtitle'=>__('food.subtitle'),'items'=>$this->content->restaurants($search),'type'=>'restaurant','search'=>$search]);}
 public function transport(Request $r,array $p=[]):void{$types=$this->content->transportTypes();View::render('modules/transport',['title'=>__('transport.title'),'types'=>$types]);}
 public function transportRequest(Request $r,array $p=[]):void{Authorization::requireLogin();if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));Response::redirect('/transport');}$pickup=trim((string)$r->post('pickup'));$destination=trim((string)$r->post('destination'));$type=(int)$r->post('vehicle_type');$v=(new Validator())->required('pickup',$pickup,__('validation.required'))->required('destination',$destination,__('validation.required'));if($v->fails()){flash('error',__('validation.required'));Response::redirect('/transport');}$this->module->createRideRequest((int)Auth::id(),$type,$pickup,$destination);flash('success',__('transport.requested'));Response::redirect('/transport');}
 public function healthcare(Request $r,array $p=[]):void{$search=trim((string)$r->query('q',''));View::render('modules/list',['title'=>__('healthcare.title'),'heading'=>__('healthcare.title'),'subtitle'=>__('healthcare.subtitle'),'items'=>$this->content->providers($search),'type'=>'provider','search'=>$search]);}
 public function education(Request $r,array $p=[]):void{$search=trim((string)$r->query('q',''));View::render('modules/list',['title'=>__('education.title'),'heading'=>__('education.title'),'subtitle'=>__('education.subtitle'),'items'=>$this->content->courses($search),'type'=>'course','search'=>$search]);}
 public function enroll(Request $r,array $p=[]):never{Authorization::requireLogin();if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));redirect_back('/education');}$this->module->enroll((int)$p['id'],(int)Auth::id());flash('success',__('education.enroll'));redirect_back('/education');}
 public function jobs(Request $r,array $p=[]):void{$search=trim((string)$r->query('q',''));View::render('modules/list',['title'=>__('jobs.title'),'heading'=>__('jobs.title'),'subtitle'=>__('jobs.subtitle'),'items'=>$this->content->jobs($search),'type'=>'job','search'=>$search]);}
 public function apply(Request $r,array $p=[]):never{Authorization::requireLogin();if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));redirect_back('/jobs');}$this->module->applyJob((int)$p['id'],(int)Auth::id(),trim((string)$r->post('cover_letter','')));flash('success',__('jobs.applied'));redirect_back('/jobs');}
 public function news(Request $r,array $p=[]):void{$search=trim((string)$r->query('q',''));View::render('modules/list',['title'=>__('news.title'),'heading'=>__('news.title'),'subtitle'=>__('news.subtitle'),'items'=>$this->content->articles(Translation::getLocale(),$search),'type'=>'article','search'=>$search]);}
 public function article(Request $r,array $p=[]):void{$a=$this->content->article((int)$p['id'],Translation::getLocale());if(!$a){http_response_code(404);View::render('errors/404');return;}View::render('modules/article',['title'=>$a['title'],'article'=>$a]);}
 public function messaging(Request $r,array $p=[]):void{Authorization::requireLogin();$conversations=$this->module->conversations((int)Auth::id());$messages=!empty($p['id'])?$this->module->messages((int)Auth::id(),(int)$p['id']):[];View::render('modules/messages',['title'=>__('messaging.title'),'conversations'=>$conversations,'messages'=>$messages,'conversationId'=>$p['id']??null]);}
 public function sendMessage(Request $r,array $p=[]):never{Authorization::requireLogin();if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));redirect_back('/messages');}$this->module->sendMessage((int)Auth::id(),(int)$p['id'],trim((string)$r->post('body')));flash('success',__('messaging.sent'));redirect_back('/messages/'.$p['id']);}
}
