<?php
declare(strict_types=1); namespace App\Controllers;
use App\Core\{Authorization,Auth,Csrf,Request,Response,Validator,View}; use App\Repositories\TransactionRepository;
final class ServiceController {
 private TransactionRepository $repo; public function __construct(){ $this->repo=new TransactionRepository(); }
 public function product(Request $r,array $p=[]):void{$item=$this->repo->product((int)$p['id']);if(!$item){http_response_code(404);View::render('errors/404');return;}View::render('modules/product',['title'=>$item['name'],'item'=>$item]);}
 public function productOrder(Request $r,array $p=[]):never{Authorization::requireLogin();if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));redirect_back('/marketplace/'.$p['id']);}$v=(new Validator())->required('address',$r->post('address'),__('validation.required'))->required('city',$r->post('city'),__('validation.required'));if($v->fails()){flash('error',__('validation.required'));redirect_back('/marketplace/'.$p['id']);}$this->repo->orderProduct((int)Auth::id(),(int)$p['id'],(int)$r->post('quantity',1),trim((string)$r->post('address')),trim((string)$r->post('city')));flash('success',__('marketplace.order_created'));Response::redirect('/dashboard');}
 public function restaurant(Request $r,array $p=[]):void{$restaurant=$this->repo->restaurant((int)$p['id']);if(!$restaurant){http_response_code(404);View::render('errors/404');return;}View::render('modules/restaurant',['title'=>$restaurant['name'],'restaurant'=>$restaurant,'menu'=>$this->repo->menu((int)$p['id'])]);}
 public function restaurantOrder(Request $r,array $p=[]):never{Authorization::requireLogin();if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));redirect_back('/food/'.$p['id']);}$this->repo->orderFood((int)Auth::id(),(int)$p['id'],(int)$r->post('menu_item_id'),(int)$r->post('quantity',1),trim((string)$r->post('address')));flash('success',__('common.created'));Response::redirect('/dashboard');}
 public function provider(Request $r,array $p=[]):void{$provider=$this->repo->provider((int)$p['id']);if(!$provider){http_response_code(404);View::render('errors/404');return;}View::render('modules/provider',['title'=>$provider['business_name'],'provider'=>$provider]);}
 public function book(Request $r,array $p=[]):never{Authorization::requireLogin();if(!Csrf::verify($r->post('_csrf'))){flash('error',__('security.csrf'));redirect_back('/healthcare/'.$p['id']);}try{$this->repo->appointment((int)Auth::id(),(int)$p['id'],(int)$r->post('service_id'),trim((string)$r->post('starts_at')),trim((string)$r->post('notes')));flash('success',__('common.created'));}catch(\Throwable $e){flash('error',$e->getMessage());}Response::redirect('/healthcare/'.$p['id']);}
}
