<?php
declare(strict_types=1);
namespace App\Repositories;
use App\Core\Repository;
final class BusinessRepository extends Repository {
 public function mine(int $userId): array { $s=$this->db->prepare('SELECT b.*,bc.name_key category_name FROM businesses b LEFT JOIN business_category_links bcl ON bcl.business_id=b.id LEFT JOIN business_categories bc ON bc.id=bcl.category_id WHERE b.owner_user_id=? AND b.deleted_at IS NULL ORDER BY b.created_at DESC');$s->execute([$userId]);return $s->fetchAll(); }
 public function all(int $limit=100): array { return $this->db->query('SELECT b.*,u.email owner_email FROM businesses b JOIN users u ON u.id=b.owner_user_id WHERE b.deleted_at IS NULL ORDER BY b.created_at DESC LIMIT '.(int)$limit)->fetchAll(); }
 public function categories(): array { return $this->db->query('SELECT * FROM business_categories ORDER BY sort_order,name_key')->fetchAll(); }
 public function create(int $owner,string $name,string $slug,string $description,?int $category): int { $this->db->beginTransaction(); try { $s=$this->db->prepare("INSERT INTO businesses(owner_user_id,name,slug,description,status) VALUES(?,?,?,?, 'pending_review')");$s->execute([$owner,$name,$slug,$description]);$id=(int)$this->db->lastInsertId();$s=$this->db->prepare('INSERT INTO business_members(business_id,user_id,role,status) VALUES(?,?,\'owner\',\'active\')');$s->execute([$id,$owner]); if($category){$s=$this->db->prepare('INSERT INTO business_category_links(business_id,category_id) VALUES(?,?)');$s->execute([$id,$category]);} $this->db->commit(); return $id;}catch(\Throwable $e){$this->db->rollBack();throw $e;} }
 public function setStatus(int $id,string $status,?int $actor=null): void { $this->db->beginTransaction();try{$this->db->prepare('UPDATE businesses SET status=?,verified_at=CASE WHEN ?=\'approved\' THEN UTC_TIMESTAMP() ELSE verified_at END WHERE id=?')->execute([$status,$status,$id]);$this->db->prepare('INSERT INTO business_status_history(business_id,status,changed_by_user_id) VALUES(?,?,?)')->execute([$id,$status,$actor]);$this->db->commit();}catch(\Throwable $e){$this->db->rollBack();throw $e;} }
 public function byOwnerProducts(int $owner): array { $s=$this->db->prepare('SELECT p.*,b.name business_name FROM products p JOIN businesses b ON b.id=p.business_id WHERE b.owner_user_id=? AND p.deleted_at IS NULL ORDER BY p.created_at DESC');$s->execute([$owner]);return $s->fetchAll(); }
 public function createProduct(int $owner,int $business,string $name,string $slug,string $description,float $price): int { $s=$this->db->prepare("INSERT INTO products(business_id,name,slug,description,base_price,currency,status,published_at) SELECT id,?,?,?,?, 'TND','published',UTC_TIMESTAMP() FROM businesses WHERE id=? AND owner_user_id=? AND deleted_at IS NULL");$s->execute([$name,$slug,$description,$price,$business,$owner]);return (int)$this->db->lastInsertId(); }
}
