<?php
declare(strict_types=1); namespace App\Repositories; use App\Core\Repository;
final class ContentRepository extends Repository {
 public function products(string $search=''): array { $sql="SELECT p.*,b.name business_name FROM products p JOIN businesses b ON b.id=p.business_id WHERE p.status='published' AND p.deleted_at IS NULL AND b.status='approved' AND b.deleted_at IS NULL"; $args=[]; if($search!==''){ $sql.=' AND (p.name LIKE ? OR p.description LIKE ? OR b.name LIKE ?)'; $q='%'.$search.'%'; $args=[$q,$q,$q]; } $sql.=' ORDER BY p.created_at DESC LIMIT 60'; $s=$this->db->prepare($sql);$s->execute($args);return $s->fetchAll(); }
 public function restaurants(string $search=''): array { $sql="SELECT r.*,b.name business_name FROM restaurants r JOIN businesses b ON b.id=r.business_id WHERE r.status='published' AND r.deleted_at IS NULL AND b.status='approved' AND b.deleted_at IS NULL"; $args=[]; if($search!==''){ $sql.=' AND (r.name LIKE ? OR r.description LIKE ? OR r.city LIKE ?)';$q='%'.$search.'%';$args=[$q,$q,$q]; } $sql.=' ORDER BY r.created_at DESC LIMIT 60';$s=$this->db->prepare($sql);$s->execute($args);return $s->fetchAll(); }
 public function transportTypes(): array { return $this->db->query('SELECT * FROM vehicle_types ORDER BY base_fare ASC')->fetchAll(); }
 public function providers(string $search=''): array { $sql="SELECT hp.*,b.name business_name FROM healthcare_providers hp JOIN businesses b ON b.id=hp.business_id WHERE hp.status='approved' AND b.status='approved'";$args=[];if($search!==''){ $sql.=' AND (hp.professional_title LIKE ? OR b.name LIKE ?)';$q='%'.$search.'%';$args=[$q,$q];}$sql.=' ORDER BY hp.created_at DESC LIMIT 60';$s=$this->db->prepare($sql);$s->execute($args);return $s->fetchAll(); }
 public function courses(string $search=''): array { $sql="SELECT c.*,ei.name institution_name FROM courses c JOIN education_institutions ei ON ei.id=c.institution_id WHERE c.status='published' AND c.deleted_at IS NULL AND ei.status='approved'";$args=[];if($search!==''){ $sql.=' AND (c.title LIKE ? OR c.description LIKE ? OR ei.name LIKE ?)';$q='%'.$search.'%';$args=[$q,$q,$q];}$sql.=' ORDER BY c.created_at DESC LIMIT 60';$s=$this->db->prepare($sql);$s->execute($args);return $s->fetchAll(); }
 public function jobs(string $search=''): array { $sql="SELECT j.*,ep.business_id,b.name business_name FROM jobs j JOIN employer_profiles ep ON ep.id=j.employer_profile_id JOIN businesses b ON b.id=ep.business_id WHERE j.status='published' AND j.deleted_at IS NULL AND b.status='approved'";$args=[];if($search!==''){ $sql.=' AND (j.title LIKE ? OR j.description LIKE ? OR b.name LIKE ?)';$q='%'.$search.'%';$args=[$q,$q,$q];}$sql.=' ORDER BY j.created_at DESC LIMIT 60';$s=$this->db->prepare($sql);$s->execute($args);return $s->fetchAll(); }
 public function articles(string $locale,string $search=''): array { $sql="SELECT a.*,at.title,at.excerpt,at.content,nc.name_key FROM articles a JOIN article_translations at ON at.article_id=a.id AND at.locale_code=? LEFT JOIN news_categories nc ON nc.id=a.category_id WHERE a.status='published' AND a.deleted_at IS NULL";$args=[$locale];if($search!==''){ $sql.=' AND (at.title LIKE ? OR at.excerpt LIKE ? OR at.content LIKE ?)';$q='%'.$search.'%';$args=[$locale,$q,$q,$q];}$sql.=' ORDER BY a.published_at DESC LIMIT 60';$s=$this->db->prepare($sql);$s->execute($args);return $s->fetchAll(); }
 public function article(int $id,string $locale): ?array { $s=$this->db->prepare("SELECT a.*,at.title,at.excerpt,at.content FROM articles a JOIN article_translations at ON at.article_id=a.id AND at.locale_code=? WHERE a.id=? AND a.status='published' LIMIT 1");$s->execute([$locale,$id]);$r=$s->fetch();if($r){$this->db->prepare('UPDATE articles SET view_count=view_count+1 WHERE id=?')->execute([$id]);}return $r?:null; }
}
