<?php
declare(strict_types=1); namespace App\Repositories; use App\Core\Repository;
final class ModuleRepository extends Repository {
 public function dashboardCounts(int $user): array { $qfn=function(string $sql)use($user){$s=$this->db->prepare($sql);$s->execute([$user]);return (int)$s->fetchColumn();}; return ['businesses'=>$qfn('SELECT COUNT(*) FROM businesses WHERE owner_user_id=? AND deleted_at IS NULL'),'orders'=>$qfn('SELECT COUNT(*) FROM marketplace_orders WHERE user_id=?'),'appointments'=>$qfn('SELECT COUNT(*) FROM appointments WHERE patient_user_id=?'),'applications'=>$qfn('SELECT COUNT(*) FROM job_applications WHERE applicant_user_id=?'),'unread'=>$qfn('SELECT COUNT(*) FROM message_reads mr JOIN messages m ON m.id=mr.message_id WHERE mr.user_id=? AND mr.read_at IS NULL'),'wallet'=>(float)$this->db->query('SELECT available_balance FROM wallet_accounts WHERE user_id='.(int)$user.' AND currency=\'TND\' LIMIT 1')->fetchColumn()]; }
 public function createRideRequest(int $user,int $type,string $pickup,string $destination): int { $s=$this->db->prepare('SELECT base_fare,per_km_fare,per_minute_fare FROM vehicle_types WHERE id=?');$s->execute([$type]);$v=$s->fetch();if(!$v)throw new \RuntimeException(__('validation.invalid'));$fare=(float)$v['base_fare'] + 5*(float)$v['per_km_fare'] + 15*(float)$v['per_minute_fare'];$number='TR'.date('YmdHis').random_int(100,999);$s=$this->db->prepare('INSERT INTO ride_requests(request_number,passenger_user_id,vehicle_type_id,pickup_address,destination_address,estimated_distance_km,estimated_duration_min,estimated_fare,currency,status) VALUES(?,?,?,?,?,5,15,?,\'TND\',\'searching\')');$s->execute([$number,$user,$type,json_encode(['address'=>$pickup],JSON_UNESCAPED_UNICODE),json_encode(['address'=>$destination],JSON_UNESCAPED_UNICODE),$fare]);return (int)$this->db->lastInsertId(); }
 public function applyJob(int $job,int $user,string $letter): void { $s=$this->db->prepare('SELECT 1 FROM job_applications WHERE job_id=? AND applicant_user_id=?');$s->execute([$job,$user]);if($s->fetchColumn())return; $s=$this->db->prepare('INSERT INTO job_applications(job_id,applicant_user_id,cover_letter,status) VALUES(?,?,?,\'submitted\')');$s->execute([$job,$user]); }
 public function enroll(int $course,int $user): void { $s=$this->db->prepare('INSERT IGNORE INTO enrollments(course_id,student_user_id,status) VALUES(?,?,\'active\')');$s->execute([$course,$user]); }
 public function createConversation(int $user,int $other,string $body): void { $this->db->beginTransaction();try{$s=$this->db->prepare('INSERT INTO conversations(type,created_by_user_id,last_message_at) VALUES(\'direct\',?,UTC_TIMESTAMP())');$s->execute([$user]);$cid=(int)$this->db->lastInsertId();$s=$this->db->prepare('INSERT INTO conversation_participants(conversation_id,user_id) VALUES(?,?),(?,?)');$s->execute([$cid,$user,$cid,$other]);$s=$this->db->prepare('INSERT INTO messages(conversation_id,sender_user_id,body,message_type,status) VALUES(?,?,?,\'text\',\'sent\')');$s->execute([$cid,$user,$body]);$this->db->commit();}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function conversations(int $user): array { $s=$this->db->prepare('SELECT c.*,m.body last_body,m.created_at message_at FROM conversations c JOIN conversation_participants cp ON cp.conversation_id=c.id LEFT JOIN messages m ON m.id=(SELECT MAX(m2.id) FROM messages m2 WHERE m2.conversation_id=c.id) WHERE cp.user_id=? ORDER BY c.last_message_at DESC');$s->execute([$user]);return $s->fetchAll(); }
 public function messages(int $user,int $conversation): array { $s=$this->db->prepare('SELECT m.*,u.email FROM messages m JOIN users u ON u.id=m.sender_user_id JOIN conversation_participants cp ON cp.conversation_id=m.conversation_id AND cp.user_id=? WHERE m.conversation_id=? ORDER BY m.created_at');$s->execute([$user,$conversation]);return $s->fetchAll(); }
 public function sendMessage(int $user,int $conversation,string $body): void { $s=$this->db->prepare('SELECT 1 FROM conversation_participants WHERE conversation_id=? AND user_id=?');$s->execute([$conversation,$user]);if(!$s->fetchColumn())throw new \RuntimeException(__('error.403'));$s=$this->db->prepare('INSERT INTO messages(conversation_id,sender_user_id,body) VALUES(?,?,?)');$s->execute([$conversation,$user,$body]);$this->db->prepare('UPDATE conversations SET last_message_at=UTC_TIMESTAMP() WHERE id=?')->execute([$conversation]); }
}
