<?php
declare(strict_types=1); namespace App\Repositories; use App\Core\Repository;
final class TransactionRepository extends Repository {
 public function product(int $id): ?array { $s=$this->db->prepare("SELECT p.*,b.name business_name FROM products p JOIN businesses b ON b.id=p.business_id WHERE p.id=? AND p.status='published' AND p.deleted_at IS NULL AND b.status='approved' LIMIT 1");$s->execute([$id]);return $s->fetch()?:null; }
 public function orderProduct(int $user,int $product,int $qty,string $address,string $city): int { $p=$this->product($product);if(!$p)throw new \RuntimeException(__('validation.invalid'));$qty=max(1,min(100,$qty));$total=(float)$p['base_price']*$qty;$number='MK'.date('YmdHis').random_int(100,999);$this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO marketplace_orders(order_number,user_id,business_id,currency,subtotal_amount,shipping_amount,discount_amount,tax_amount,total_amount,status,payment_status,placed_at) VALUES(?,?,?,'TND',?,0,0,0,?,'pending','unpaid',UTC_TIMESTAMP())");$s->execute([$number,$user,$p['business_id'],$total,$total]);$oid=(int)$this->db->lastInsertId();$s=$this->db->prepare('INSERT INTO marketplace_order_items(order_id,product_id,product_name,sku,quantity,unit_price,total_price) VALUES(?,?,?,?,?,?,?)');$s->execute([$oid,$product,$p['name'],$p['sku'],$qty,$p['base_price'],$total]);$s=$this->db->prepare('INSERT INTO shipping_addresses(order_id,recipient_name,address_line1,city,country_code) VALUES(?,(SELECT COALESCE(display_name,email) FROM user_profiles up JOIN users u ON u.id=up.user_id WHERE up.user_id=?),?,? ,\'TN\')');$s->execute([$oid,$user,$address,$city]);$this->db->commit();return $oid;}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function restaurant(int $id): ?array { $s=$this->db->prepare("SELECT r.*,b.name business_name FROM restaurants r JOIN businesses b ON b.id=r.business_id WHERE r.id=? AND r.status='published' AND r.deleted_at IS NULL LIMIT 1");$s->execute([$id]);return $s->fetch()?:null; }
 public function menu(int $restaurant): array { $s=$this->db->prepare('SELECT mi.*,mc.name category_name FROM menu_items mi JOIN menu_categories mc ON mc.id=mi.menu_category_id WHERE mc.restaurant_id=? AND mi.is_available=1 AND mi.deleted_at IS NULL ORDER BY mc.sort_order,mi.sort_order,mi.name');$s->execute([$restaurant]);return $s->fetchAll(); }
 public function orderFood(int $user,int $restaurant,int $item,int $qty,string $address): int { $r=$this->restaurant($restaurant);$s=$this->db->prepare('SELECT mi.* FROM menu_items mi JOIN menu_categories mc ON mc.id=mi.menu_category_id WHERE mi.id=? AND mc.restaurant_id=? AND mi.is_available=1 AND mi.deleted_at IS NULL LIMIT 1');$s->execute([$item,$restaurant]);$mi=$s->fetch();if(!$r||!$mi)throw new \RuntimeException(__('validation.invalid'));$qty=max(1,min(50,$qty));$subtotal=(float)$mi['price']*$qty;$total=$subtotal+(float)$r['delivery_fee'];$number='FD'.date('YmdHis').random_int(100,999);$this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO food_orders(order_number,user_id,restaurant_id,currency,subtotal_amount,delivery_fee,discount_amount,tax_amount,total_amount,status,payment_status,delivery_address,placed_at) VALUES(?,?,?,'TND',?,?,0,0,?,'pending','unpaid',?,UTC_TIMESTAMP())");$s->execute([$number,$user,$restaurant,$subtotal,$r['delivery_fee'],$total,json_encode(['address'=>$address],JSON_UNESCAPED_UNICODE)]);$oid=(int)$this->db->lastInsertId();$s=$this->db->prepare('INSERT INTO food_order_items(order_id,menu_item_id,item_name,quantity,unit_price,total_price) VALUES(?,?,?,?,?,?)');$s->execute([$oid,$item,$mi['name'],$qty,$mi['price'],$subtotal]);$this->db->commit();return $oid;}catch(\Throwable $e){$this->db->rollBack();throw $e;}}
 public function provider(int $id): ?array { $s=$this->db->prepare("SELECT hp.*,b.name business_name FROM healthcare_providers hp JOIN businesses b ON b.id=hp.business_id WHERE hp.id=? AND hp.status='approved' LIMIT 1");$s->execute([$id]);$p=$s->fetch();if(!$p)return null;$s=$this->db->prepare('SELECT hs.*,ps.provider_id FROM healthcare_services hs JOIN provider_services ps ON ps.service_id=hs.id WHERE ps.provider_id=? AND hs.status=\'active\' ORDER BY hs.name');$s->execute([$id]);$p['services']=$s->fetchAll();return $p; }
 public function appointment(int $user,int $provider,int $service,string $start,string $notes): int { $p=$this->provider($provider);$found=null;foreach($p['services']??[] as $x)if((int)$x['id']===$service)$found=$x;if(!$p||!$found)throw new \RuntimeException(__('validation.invalid'));$dt=new \DateTime($start);$end=(clone $dt)->modify('+'.(int)$found['duration_minutes'].' minutes');$check=$this->db->prepare("SELECT 1 FROM appointments WHERE provider_id=? AND status IN ('pending','confirmed') AND starts_at < ? AND ends_at > ? LIMIT 1");$check->execute([$provider,$end->format('Y-m-d H:i:s'),$dt->format('Y-m-d H:i:s')]);if($check->fetchColumn())throw new \RuntimeException(__('validation.invalid'));$number='AP'.date('YmdHis').random_int(100,999);$s=$this->db->prepare('INSERT INTO appointments(appointment_number,patient_user_id,provider_id,service_id,starts_at,ends_at,status,price,currency,patient_notes) VALUES(?,?,?,?,?,?,\'pending\',?,\'TND\',?)');$s->execute([$number,$user,$provider,$service,$dt->format('Y-m-d H:i:s'),$end->format('Y-m-d H:i:s'),$found['price'],$notes]);return (int)$this->db->lastInsertId();}
}
