<?php
declare(strict_types=1);
namespace App\Repositories;
use App\Core\Repository;
final class UserRepository extends Repository {
 public function findById(int $id): ?array { $s=$this->db->prepare('SELECT u.*, p.first_name,p.last_name,p.display_name,p.preferred_locale,p.avatar_media_id FROM users u LEFT JOIN user_profiles p ON p.user_id=u.id WHERE u.id=? AND u.deleted_at IS NULL LIMIT 1'); $s->execute([$id]); return $s->fetch() ?: null; }
 public function findByEmail(string $email): ?array { $s=$this->db->prepare('SELECT * FROM users WHERE email=? AND deleted_at IS NULL LIMIT 1'); $s->execute([mb_strtolower(trim($email))]); return $s->fetch() ?: null; }
 public function create(array $data): int { $s=$this->db->prepare('INSERT INTO users(email,phone,password_hash,status) VALUES(?,?,?,\'active\')'); $s->execute([$data['email']?:null,$data['phone']?:null,$data['password_hash']]); $id=(int)$this->db->lastInsertId(); $s=$this->db->prepare('INSERT INTO user_profiles(user_id,first_name,last_name,display_name,preferred_locale) VALUES(?,?,?,?,?)'); $s->execute([$id,$data['first_name']??null,$data['last_name']??null,$data['display_name']??null,$data['locale']??'fr']); $s=$this->db->prepare("INSERT INTO user_roles(user_id,role_id) SELECT ?, id FROM roles WHERE slug='user'"); $s->execute([$id]); $s=$this->db->prepare('INSERT INTO wallet_accounts(user_id,currency,status) VALUES(?,\'TND\',\'active\')'); $s->execute([$id]); return $id; }
 public function updateLoginSuccess(int $id): void { $s=$this->db->prepare('UPDATE users SET last_login_at=UTC_TIMESTAMP(), last_login_ip=INET6_ATON(?), failed_login_count=0, locked_until=NULL WHERE id=?'); $s->execute([$_SERVER['REMOTE_ADDR']??'0.0.0.0',$id]); }
 public function updateLoginFailure(int $id,int $count,?string $until): void { $s=$this->db->prepare('UPDATE users SET failed_login_count=?, locked_until=? WHERE id=?'); $s->execute([$count,$until,$id]); }
 public function updateLocale(?int $id,string $locale): void { if(!$id)return; $s=$this->db->prepare('UPDATE user_profiles SET preferred_locale=? WHERE user_id=?'); $s->execute([$locale,$id]); }
 public function hasRole(int $id,string $role): bool { $s=$this->db->prepare('SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND r.slug=? LIMIT 1'); $s->execute([$id,$role]); return (bool)$s->fetchColumn(); }
 public function hasPermission(int $id,string $permission): bool { $s=$this->db->prepare('SELECT 1 FROM user_roles ur JOIN role_permissions rp ON rp.role_id=ur.role_id JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=? AND p.slug=? LIMIT 1'); $s->execute([$id,$permission]); return (bool)$s->fetchColumn(); }
 public function addRememberToken(int $userId,string $rawToken,string $expires): void { $s=$this->db->prepare('INSERT INTO remember_tokens(user_id,token_hash,expires_at) VALUES(?,?,?)'); $s->execute([$userId,hash('sha256',$rawToken),$expires]); }
 public function findRememberToken(string $rawToken): ?array { $s=$this->db->prepare('SELECT rt.*,u.* FROM remember_tokens rt JOIN users u ON u.id=rt.user_id WHERE rt.token_hash=? AND rt.expires_at>UTC_TIMESTAMP() AND u.status=\'active\' AND u.deleted_at IS NULL LIMIT 1'); $s->execute([hash('sha256',$rawToken)]); return $s->fetch() ?: null; }
 public function purgeRememberTokens(): void { $this->db->exec('DELETE FROM remember_tokens WHERE expires_at <= UTC_TIMESTAMP()'); }
 public function createResetToken(int $userId,string $rawToken,string $expires): void { $this->db->prepare('UPDATE password_reset_tokens SET used_at=UTC_TIMESTAMP() WHERE user_id=? AND used_at IS NULL')->execute([$userId]); $s=$this->db->prepare('INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,?)'); $s->execute([$userId,hash('sha256',$rawToken),$expires]); }
 public function findResetToken(string $rawToken): ?array { $s=$this->db->prepare('SELECT prt.*,u.email FROM password_reset_tokens prt JOIN users u ON u.id=prt.user_id WHERE prt.token_hash=? AND prt.used_at IS NULL AND prt.expires_at>UTC_TIMESTAMP() AND u.deleted_at IS NULL LIMIT 1'); $s->execute([hash('sha256',$rawToken)]); return $s->fetch() ?: null; }
 public function resetPassword(int $userId,int $tokenId,string $hash): void { $this->db->beginTransaction(); try { $s=$this->db->prepare('UPDATE users SET password_hash=? WHERE id=?'); $s->execute([$hash,$userId]); $s=$this->db->prepare('UPDATE password_reset_tokens SET used_at=UTC_TIMESTAMP() WHERE id=?'); $s->execute([$tokenId]); $s=$this->db->prepare('DELETE FROM remember_tokens WHERE user_id=?'); $s->execute([$userId]); $this->db->commit(); } catch(\Throwable $e){$this->db->rollBack();throw $e;} }
 public function stats(): array { return ['users'=>(int)$this->db->query('SELECT COUNT(*) FROM users WHERE deleted_at IS NULL')->fetchColumn(),'businesses'=>(int)$this->db->query('SELECT COUNT(*) FROM businesses WHERE deleted_at IS NULL')->fetchColumn(),'products'=>(int)$this->db->query('SELECT COUNT(*) FROM products WHERE deleted_at IS NULL')->fetchColumn(),'articles'=>(int)$this->db->query('SELECT COUNT(*) FROM articles WHERE deleted_at IS NULL')->fetchColumn()]; }
}
